name: Buycraft
main: net.buycraft.Plugin
version: 6.8.2
author: Tebex Limited
website: http://buycraft.net
commands:
   buycraft:
      usage: /<command> <reload/forcecheck/secret/payments <ign>>
   buysign:
      usage: /<command> <begin/end/filter [Package ID]>